export default {
  UPDATE_EDITOR: "UPDATE_EDITOR",
  SAVE: "SAVE",
  SAVE_SUCCESS: "SAVE_SUCCESS",
  OPEN: "OPEN",
  OPEN_SUCCESS: "OPEN_SUCCESS",
  SAVE_CONFLICT: "SAVE_CONFLICT",
  FORCE_SAVE: "FORCE_SAVE",
  FORCE_SAVE_SUCCESS: "FORCE_SAVE_SUCCESS"
};
