
const PREFIX = '@@koala-redux'

export default {
  DB_READY: `${PREFIX}/DB_READY`,
  CHANGE: `${PREFIX}/CHANGE`,
  PAUSED: `${PREFIX}/PAUSED`,
  ACTIVE: `${PREFIX}/ACTIVE`,
  DENIED: `${PREFIX}/DENIED`,
  COMPLETE: `${PREFIX}/COMPLETE`,
  ERROR: `${PREFIX}/ERROR`
}
